"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Miguelangelo Rosario (https://sketchfab.com/miguelangelo2k)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/just-people-9310a99c9ee54a1d9f4b51a152441813
Title: Just People
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from "three";

// Define a more specific type for the nodes
type GLTFNodes = {
  _rootJoint: THREE.Bone;
  [key: string]: THREE.Object3D & {
    geometry?: THREE.BufferGeometry;
    material?: THREE.Material | THREE.Material[];
    skeleton?: any;
  };
};

type GLTFResult = {
  nodes: GLTFNodes;
  materials: {
    [key: string]: THREE.Material;
  };
  animations: THREE.AnimationClip[];
};

// Define props type
type ModelProps = {
  [key: string]: any;
};

export function Model(props: ModelProps) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/Just People 3D Model.glb') as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // Log available animations
    
    // Play all animations
    Object.values(actions).forEach((action) => {
      if (action) {
        action.reset().play()
        action.setLoop(2201, 2) // THREE.LoopRepeat
        action.clampWhenFinished = false
      }
    })
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
          <group name="2f748de034ff44328e4a07838bd38921fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.mtl_Mnnlich000Skin_001_Color}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.mtl_Weiblich005Skin_001_Color}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials.mtl_Mnnlich005Skin_001_Color}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    name="Object_14"
                    geometry={nodes.Object_14.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_14.skeleton}
                  />
                  <skinnedMesh
                    name="Object_16"
                    geometry={nodes.Object_16.geometry}
                    material={materials.mtl_Weiblich008Skin_001_Color}
                    skeleton={nodes.Object_16.skeleton}
                  />
                  <skinnedMesh
                    name="Object_17"
                    geometry={nodes.Object_17.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_17.skeleton}
                  />
                  <skinnedMesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    material={materials.mtl_Weiblich007Skin_001_Color}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <skinnedMesh
                    name="Object_20"
                    geometry={nodes.Object_20.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_20.skeleton}
                  />
                  <skinnedMesh
                    name="Object_22"
                    geometry={nodes.Object_22.geometry}
                    material={materials.mtl_Weiblich006Skin_001_Color}
                    skeleton={nodes.Object_22.skeleton}
                  />
                  <skinnedMesh
                    name="Object_23"
                    geometry={nodes.Object_23.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_23.skeleton}
                  />
                  <skinnedMesh
                    name="Object_25"
                    geometry={nodes.Object_25.geometry}
                    material={materials.mtl_Mnnlich006Skin_001_Color}
                    skeleton={nodes.Object_25.skeleton}
                  />
                  <skinnedMesh
                    name="Object_26"
                    geometry={nodes.Object_26.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_26.skeleton}
                  />
                  <skinnedMesh
                    name="Object_28"
                    geometry={nodes.Object_28.geometry}
                    material={materials.mtl_Mnnlich007Skin_001_Color}
                    skeleton={nodes.Object_28.skeleton}
                  />
                  <skinnedMesh
                    name="Object_29"
                    geometry={nodes.Object_29.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_29.skeleton}
                  />
                  <skinnedMesh
                    name="Object_31"
                    geometry={nodes.Object_31.geometry}
                    material={materials.mtl_Mnnlich008Skin_001_Color}
                    skeleton={nodes.Object_31.skeleton}
                  />
                  <skinnedMesh
                    name="Object_32"
                    geometry={nodes.Object_32.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_32.skeleton}
                  />
                  <skinnedMesh
                    name="Object_34"
                    geometry={nodes.Object_34.geometry}
                    material={materials.mtl_Mnnlich009Skin_001_Color}
                    skeleton={nodes.Object_34.skeleton}
                  />
                  <skinnedMesh
                    name="Object_35"
                    geometry={nodes.Object_35.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_35.skeleton}
                  />
                  <skinnedMesh
                    name="Object_37"
                    geometry={nodes.Object_37.geometry}
                    material={materials.mtl_Mnnlich010Skin_001_Color}
                    skeleton={nodes.Object_37.skeleton}
                  />
                  <skinnedMesh
                    name="Object_38"
                    geometry={nodes.Object_38.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_38.skeleton}
                  />
                  <skinnedMesh
                    name="Object_40"
                    geometry={nodes.Object_40.geometry}
                    material={materials.mtl_Mnnlich001Skin_001_Color}
                    skeleton={nodes.Object_40.skeleton}
                  />
                  <skinnedMesh
                    name="Object_41"
                    geometry={nodes.Object_41.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_41.skeleton}
                  />
                  <skinnedMesh
                    name="Object_43"
                    geometry={nodes.Object_43.geometry}
                    material={materials.mtl_Weiblich003Skin_001_Color}
                    skeleton={nodes.Object_43.skeleton}
                  />
                  <skinnedMesh
                    name="Object_44"
                    geometry={nodes.Object_44.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_44.skeleton}
                  />
                  <skinnedMesh
                    name="Object_46"
                    geometry={nodes.Object_46.geometry}
                    material={materials.mtl_Weiblich000Skin_001_Color}
                    skeleton={nodes.Object_46.skeleton}
                  />
                  <skinnedMesh
                    name="Object_47"
                    geometry={nodes.Object_47.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_47.skeleton}
                  />
                  <skinnedMesh
                    name="Object_49"
                    geometry={nodes.Object_49.geometry}
                    material={materials.mtl_Weiblich001Skin_001_Color}
                    skeleton={nodes.Object_49.skeleton}
                  />
                  <skinnedMesh
                    name="Object_50"
                    geometry={nodes.Object_50.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_50.skeleton}
                  />
                  <skinnedMesh
                    name="Object_52"
                    geometry={nodes.Object_52.geometry}
                    material={materials.mtl_Weiblich002Skin_001_Color}
                    skeleton={nodes.Object_52.skeleton}
                  />
                  <skinnedMesh
                    name="Object_53"
                    geometry={nodes.Object_53.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_53.skeleton}
                  />
                  <skinnedMesh
                    name="Object_55"
                    geometry={nodes.Object_55.geometry}
                    material={materials.mtl_Weiblich004Skin_001_Color}
                    skeleton={nodes.Object_55.skeleton}
                  />
                  <skinnedMesh
                    name="Object_56"
                    geometry={nodes.Object_56.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_56.skeleton}
                  />
                  <skinnedMesh
                    name="Object_58"
                    geometry={nodes.Object_58.geometry}
                    material={materials.mtl_Mnnlich004Skin_001_Color}
                    skeleton={nodes.Object_58.skeleton}
                  />
                  <skinnedMesh
                    name="Object_59"
                    geometry={nodes.Object_59.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_59.skeleton}
                  />
                  <skinnedMesh
                    name="Object_61"
                    geometry={nodes.Object_61.geometry}
                    material={materials.mtl_Mnnlich003Skin_001_Color}
                    skeleton={nodes.Object_61.skeleton}
                  />
                  <skinnedMesh
                    name="Object_62"
                    geometry={nodes.Object_62.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_62.skeleton}
                  />
                  <skinnedMesh
                    name="Object_64"
                    geometry={nodes.Object_64.geometry}
                    material={materials.mtl_Mnnlich002Skin_001_Color}
                    skeleton={nodes.Object_64.skeleton}
                  />
                  <skinnedMesh
                    name="Object_65"
                    geometry={nodes.Object_65.geometry}
                    material={materials.Populate_Custom_Skin}
                    skeleton={nodes.Object_65.skeleton}
                  />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_9" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_12" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_15" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_18" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_21" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_24" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_27" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_30" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_33" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_36" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_39" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_42" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_45" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_48" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_51" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_54" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_57" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_60" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_63" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich000Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Weiblich005Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich005Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Weiblich008Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Weiblich007Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Weiblich006Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich006Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich007Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich008Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich009Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich010Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich011Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich012Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich013Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich014Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich015Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich016Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich001Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Weiblich003Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Weiblich000Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Weiblich001Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Weiblich002Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Weiblich004Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich004Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich003Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M��nnlich002Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Weiblich009Skin_001" rotation={[-Math.PI / 2, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Just People 3D Model.glb')
